esphome:
  name: d1-mini-water-flow
  friendly_name: D1 mini Water flow

esp8266:
  board: d1_mini

# Enable logging
logger:
  level: debug
debug:
  update_interval: 60s

button:
  - platform: restart
    name: "IoT Restart"

text_sensor:
  - platform: debug
    device:
      name: "Device Info"
    reset_reason:
      name: "Reset Reason"
# Enable Home Assistant API
api:
  encryption:
    key: "ZLILOe7ltSY9ucBgVexeD/nBW17vuuhLmInOIWOuxwQ="
  services:
      - service: reset_daily_water_consumption
        then:
          - sensor.integration.reset: daily_water_consumption
ota:
  - platform: esphome
    password: "XXXX"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.16
    gateway: 192.168.1.1
    subnet: 255.255.255.0
  use_address: 192.168.1.16
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "D1-Mini-Water-Flow"
    password: "XXXXXXXXXXXX"

captive_portal:

sensor:
  - platform: pulse_meter
    pin: D5
    name: "Water Flow Rate"
    id: water_flow_rate
    unit_of_measurement: 'L/min'
    icon: "mdi:water"
    accuracy_decimals: 2
    timeout: 1s
    filters:
      - multiply: 0.00168  # (1 pulse = 0.00168 liters) # F =(10 * Q-5) 5%, F is the frequency Q is L/Min That is, 595 pulses per liter of water

  # Daily Water Consumption (Liters)
  - platform: integration
    id: daily_water_consumption
    name: "Daily Water Consumption"
    sensor: water_flow_rate
    time_unit: min
    unit_of_measurement: "L"
    accuracy_decimals: 2
    restore: false
    integration_method: trapezoid
